base_url: "http://185.232.71.249:8002"
login: "/token"
headers:
  login_header:
    "accept": "application/json"
    "Content-Type": "application/x-www-form-urlencoded"
  token_header:
    "accept": "application/json"
    "authorization": ""

users:
  my_user: "/users/me"

